language: python
python:
  - "3.4"
  - "3.5"
services:
    - mysql
    - redis-server
before_script:
  - mysql -e 'create database `goteo-test`;'
  - mysql goteo-test < goteoapi/tests/sql/schema_mysql.sql
  - mysql goteo-test < goteoapi/tests/sql/data_mysql.sql
install:
    - pip install -r requirements.txt
    - pip install -r goteoapi_*/requirements.txt
env:
    - GOTEO_API_CONFIG_FILE="$TRAVIS_BUILD_DIR/config_test.py.dist"
script: nosetests
