version: "3.6"
services:
  mariadb:
    image: mariadb:10.2
    container_name: goteo-api-mariadb
    working_dir: /application
    volumes:
      - goteo-api-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=crowdfunding
      - MYSQL_DATABASE=goteo
      - MYSQL_USER=goteo
      - MYSQL_PASSWORD=goteo
    ports:
      - "3308:3306"

  webserver:
    image: nginx:alpine
    container_name: api-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8083:80"

  php:
    build: .
    container_name: goteo-api
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - goteo-geoip:/usr/share/GeoIP
    environment:
      - GOTEO_CONFIG_FILE
      - DEBUG
      - UID
    command: ./docker/php/init.sh

volumes:
  goteo-api-mariadb:
